# These are supported funding model platforms

github: [selfishprimate]  # GitHub Sponsors
patreon: selfishprimate  # Patreon
# open_collective: kullaniciadi
# ko_fi: kullaniciadi
# tidelift: platform-name/package-name
# community_bridge: project-name
# liberapay: kullaniciadi
# issuehunt: kullaniciadi
# otechie: kullaniciadi
# lfx_crowdfunding: project-name
custom: ['https://buymeacoffee.com/selfishprimate']  # Buy Me a Coffee