# These are supported funding model platforms

github: [selfishprimate]  # GitHub Sponsors kullanıcı adınız
# patreon: kullaniciadi
# open_collective: kullaniciadi
ko_fi: selfishprimate  # Ko-fi kullanıcı adınız
# tidelift: platform-name/package-name
# community_bridge: project-name
# liberapay: kullaniciadi
# issuehunt: kullaniciadi
# otechie: kullaniciadi
# lfx_crowdfunding: project-name
custom: ['https://buymeacoffee.com/selfishprimate']  # Özel bağış bağlantıları